# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GeneralListeValeur(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, value: List[str]=None):  # noqa: E501
        """GeneralListeValeur - a model defined in Swagger

        :param value: The value of this GeneralListeValeur.  # noqa: E501
        :type value: List[str]
        """
        self.swagger_types = {
            'value': List[str]
        }

        self.attribute_map = {
            'value': 'value'
        }
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'GeneralListeValeur':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The general_liste_valeur of this GeneralListeValeur.  # noqa: E501
        :rtype: GeneralListeValeur
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> List[str]:
        """Gets the value of this GeneralListeValeur.


        :return: The value of this GeneralListeValeur.
        :rtype: List[str]
        """
        return self._value

    @value.setter
    def value(self, value: List[str]):
        """Sets the value of this GeneralListeValeur.


        :param value: The value of this GeneralListeValeur.
        :type value: List[str]
        """

        self._value = value
