# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class GeodataEdition(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, fichier_data: str=None, fichier_meta: str=None):  # noqa: E501
        """GeodataEdition - a model defined in Swagger

        :param fichier_data: The fichier_data of this GeodataEdition.  # noqa: E501
        :type fichier_data: str
        :param fichier_meta: The fichier_meta of this GeodataEdition.  # noqa: E501
        :type fichier_meta: str
        """
        self.swagger_types = {
            'fichier_data': str,
            'fichier_meta': str
        }

        self.attribute_map = {
            'fichier_data': 'fichier_data',
            'fichier_meta': 'fichier_meta'
        }
        self._fichier_data = fichier_data
        self._fichier_meta = fichier_meta

    @classmethod
    def from_dict(cls, dikt) -> 'GeodataEdition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The geodata_edition of this GeodataEdition.  # noqa: E501
        :rtype: GeodataEdition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fichier_data(self) -> str:
        """Gets the fichier_data of this GeodataEdition.


        :return: The fichier_data of this GeodataEdition.
        :rtype: str
        """
        return self._fichier_data

    @fichier_data.setter
    def fichier_data(self, fichier_data: str):
        """Sets the fichier_data of this GeodataEdition.


        :param fichier_data: The fichier_data of this GeodataEdition.
        :type fichier_data: str
        """

        self._fichier_data = fichier_data

    @property
    def fichier_meta(self) -> str:
        """Gets the fichier_meta of this GeodataEdition.


        :return: The fichier_meta of this GeodataEdition.
        :rtype: str
        """
        return self._fichier_meta

    @fichier_meta.setter
    def fichier_meta(self, fichier_meta: str):
        """Sets the fichier_meta of this GeodataEdition.


        :param fichier_meta: The fichier_meta of this GeodataEdition.
        :type fichier_meta: str
        """

        self._fichier_meta = fichier_meta
