# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suivi_prod_unite_travail2_no_rel import SuiviProdUniteTravail2NoRel  # noqa: F401,E501
from swagger_server.models.suivi_produnite_travail2full_rel_relation import SuiviProduniteTravail2fullRelRelation  # noqa: F401,E501
from swagger_server import util


class SuiviProdUniteTravail2FullRel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, unite_travail_2: SuiviProdUniteTravail2NoRel=None, relation: SuiviProduniteTravail2fullRelRelation=None):  # noqa: E501
        """SuiviProdUniteTravail2FullRel - a model defined in Swagger

        :param unite_travail_2: The unite_travail_2 of this SuiviProdUniteTravail2FullRel.  # noqa: E501
        :type unite_travail_2: SuiviProdUniteTravail2NoRel
        :param relation: The relation of this SuiviProdUniteTravail2FullRel.  # noqa: E501
        :type relation: SuiviProduniteTravail2fullRelRelation
        """
        self.swagger_types = {
            'unite_travail_2': SuiviProdUniteTravail2NoRel,
            'relation': SuiviProduniteTravail2fullRelRelation
        }

        self.attribute_map = {
            'unite_travail_2': 'unite_travail_2',
            'relation': 'relation'
        }
        self._unite_travail_2 = unite_travail_2
        self._relation = relation

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdUniteTravail2FullRel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prod-unite_travail_2-full_rel of this SuiviProdUniteTravail2FullRel.  # noqa: E501
        :rtype: SuiviProdUniteTravail2FullRel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def unite_travail_2(self) -> SuiviProdUniteTravail2NoRel:
        """Gets the unite_travail_2 of this SuiviProdUniteTravail2FullRel.


        :return: The unite_travail_2 of this SuiviProdUniteTravail2FullRel.
        :rtype: SuiviProdUniteTravail2NoRel
        """
        return self._unite_travail_2

    @unite_travail_2.setter
    def unite_travail_2(self, unite_travail_2: SuiviProdUniteTravail2NoRel):
        """Sets the unite_travail_2 of this SuiviProdUniteTravail2FullRel.


        :param unite_travail_2: The unite_travail_2 of this SuiviProdUniteTravail2FullRel.
        :type unite_travail_2: SuiviProdUniteTravail2NoRel
        """

        self._unite_travail_2 = unite_travail_2

    @property
    def relation(self) -> SuiviProduniteTravail2fullRelRelation:
        """Gets the relation of this SuiviProdUniteTravail2FullRel.


        :return: The relation of this SuiviProdUniteTravail2FullRel.
        :rtype: SuiviProduniteTravail2fullRelRelation
        """
        return self._relation

    @relation.setter
    def relation(self, relation: SuiviProduniteTravail2fullRelRelation):
        """Sets the relation of this SuiviProdUniteTravail2FullRel.


        :param relation: The relation of this SuiviProdUniteTravail2FullRel.
        :type relation: SuiviProduniteTravail2fullRelRelation
        """

        self._relation = relation
