# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suivi_prod_etape_sut import SuiviProdEtapeSut  # noqa: F401,E501
from swagger_server import util


class SuiviProdsousUniteTravailfullRelRelation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, etape_sut: List[SuiviProdEtapeSut]=None):  # noqa: E501
        """SuiviProdsousUniteTravailfullRelRelation - a model defined in Swagger

        :param etape_sut: The etape_sut of this SuiviProdsousUniteTravailfullRelRelation.  # noqa: E501
        :type etape_sut: List[SuiviProdEtapeSut]
        """
        self.swagger_types = {
            'etape_sut': List[SuiviProdEtapeSut]
        }

        self.attribute_map = {
            'etape_sut': 'etape_sut'
        }
        self._etape_sut = etape_sut

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdsousUniteTravailfullRelRelation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prodsous_unite_travailfull_rel_relation of this SuiviProdsousUniteTravailfullRelRelation.  # noqa: E501
        :rtype: SuiviProdsousUniteTravailfullRelRelation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def etape_sut(self) -> List[SuiviProdEtapeSut]:
        """Gets the etape_sut of this SuiviProdsousUniteTravailfullRelRelation.


        :return: The etape_sut of this SuiviProdsousUniteTravailfullRelRelation.
        :rtype: List[SuiviProdEtapeSut]
        """
        return self._etape_sut

    @etape_sut.setter
    def etape_sut(self, etape_sut: List[SuiviProdEtapeSut]):
        """Sets the etape_sut of this SuiviProdsousUniteTravailfullRelRelation.


        :param etape_sut: The etape_sut of this SuiviProdsousUniteTravailfullRelRelation.
        :type etape_sut: List[SuiviProdEtapeSut]
        """

        self._etape_sut = etape_sut
