# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuiviProdEtapeUt(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, etampe: str=None, dt_c: str=None, dt_m: str=None, id: str=None, id_ut: str=None, nom_etape_cl: int=None, description: str=None, operateur: str=None, date_debut: str=None, date_fin: str=None, statut_etape_cl: int=None):  # noqa: E501
        """SuiviProdEtapeUt - a model defined in Swagger

        :param etampe: The etampe of this SuiviProdEtapeUt.  # noqa: E501
        :type etampe: str
        :param dt_c: The dt_c of this SuiviProdEtapeUt.  # noqa: E501
        :type dt_c: str
        :param dt_m: The dt_m of this SuiviProdEtapeUt.  # noqa: E501
        :type dt_m: str
        :param id: The id of this SuiviProdEtapeUt.  # noqa: E501
        :type id: str
        :param id_ut: The id_ut of this SuiviProdEtapeUt.  # noqa: E501
        :type id_ut: str
        :param nom_etape_cl: The nom_etape_cl of this SuiviProdEtapeUt.  # noqa: E501
        :type nom_etape_cl: int
        :param description: The description of this SuiviProdEtapeUt.  # noqa: E501
        :type description: str
        :param operateur: The operateur of this SuiviProdEtapeUt.  # noqa: E501
        :type operateur: str
        :param date_debut: The date_debut of this SuiviProdEtapeUt.  # noqa: E501
        :type date_debut: str
        :param date_fin: The date_fin of this SuiviProdEtapeUt.  # noqa: E501
        :type date_fin: str
        :param statut_etape_cl: The statut_etape_cl of this SuiviProdEtapeUt.  # noqa: E501
        :type statut_etape_cl: int
        """
        self.swagger_types = {
            'etampe': str,
            'dt_c': str,
            'dt_m': str,
            'id': str,
            'id_ut': str,
            'nom_etape_cl': int,
            'description': str,
            'operateur': str,
            'date_debut': str,
            'date_fin': str,
            'statut_etape_cl': int
        }

        self.attribute_map = {
            'etampe': 'etampe',
            'dt_c': 'dt_c',
            'dt_m': 'dt_m',
            'id': 'id',
            'id_ut': 'id_ut',
            'nom_etape_cl': 'nom_etape_cl',
            'description': 'description',
            'operateur': 'operateur',
            'date_debut': 'date_debut',
            'date_fin': 'date_fin',
            'statut_etape_cl': 'statut_etape_cl'
        }
        self._etampe = etampe
        self._dt_c = dt_c
        self._dt_m = dt_m
        self._id = id
        self._id_ut = id_ut
        self._nom_etape_cl = nom_etape_cl
        self._description = description
        self._operateur = operateur
        self._date_debut = date_debut
        self._date_fin = date_fin
        self._statut_etape_cl = statut_etape_cl

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdEtapeUt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prod-etape_ut of this SuiviProdEtapeUt.  # noqa: E501
        :rtype: SuiviProdEtapeUt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def etampe(self) -> str:
        """Gets the etampe of this SuiviProdEtapeUt.


        :return: The etampe of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._etampe

    @etampe.setter
    def etampe(self, etampe: str):
        """Sets the etampe of this SuiviProdEtapeUt.


        :param etampe: The etampe of this SuiviProdEtapeUt.
        :type etampe: str
        """

        self._etampe = etampe

    @property
    def dt_c(self) -> str:
        """Gets the dt_c of this SuiviProdEtapeUt.


        :return: The dt_c of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._dt_c

    @dt_c.setter
    def dt_c(self, dt_c: str):
        """Sets the dt_c of this SuiviProdEtapeUt.


        :param dt_c: The dt_c of this SuiviProdEtapeUt.
        :type dt_c: str
        """

        self._dt_c = dt_c

    @property
    def dt_m(self) -> str:
        """Gets the dt_m of this SuiviProdEtapeUt.


        :return: The dt_m of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._dt_m

    @dt_m.setter
    def dt_m(self, dt_m: str):
        """Sets the dt_m of this SuiviProdEtapeUt.


        :param dt_m: The dt_m of this SuiviProdEtapeUt.
        :type dt_m: str
        """

        self._dt_m = dt_m

    @property
    def id(self) -> str:
        """Gets the id of this SuiviProdEtapeUt.


        :return: The id of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this SuiviProdEtapeUt.


        :param id: The id of this SuiviProdEtapeUt.
        :type id: str
        """

        self._id = id

    @property
    def id_ut(self) -> str:
        """Gets the id_ut of this SuiviProdEtapeUt.


        :return: The id_ut of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._id_ut

    @id_ut.setter
    def id_ut(self, id_ut: str):
        """Sets the id_ut of this SuiviProdEtapeUt.


        :param id_ut: The id_ut of this SuiviProdEtapeUt.
        :type id_ut: str
        """

        self._id_ut = id_ut

    @property
    def nom_etape_cl(self) -> int:
        """Gets the nom_etape_cl of this SuiviProdEtapeUt.


        :return: The nom_etape_cl of this SuiviProdEtapeUt.
        :rtype: int
        """
        return self._nom_etape_cl

    @nom_etape_cl.setter
    def nom_etape_cl(self, nom_etape_cl: int):
        """Sets the nom_etape_cl of this SuiviProdEtapeUt.


        :param nom_etape_cl: The nom_etape_cl of this SuiviProdEtapeUt.
        :type nom_etape_cl: int
        """

        self._nom_etape_cl = nom_etape_cl

    @property
    def description(self) -> str:
        """Gets the description of this SuiviProdEtapeUt.


        :return: The description of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this SuiviProdEtapeUt.


        :param description: The description of this SuiviProdEtapeUt.
        :type description: str
        """

        self._description = description

    @property
    def operateur(self) -> str:
        """Gets the operateur of this SuiviProdEtapeUt.


        :return: The operateur of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._operateur

    @operateur.setter
    def operateur(self, operateur: str):
        """Sets the operateur of this SuiviProdEtapeUt.


        :param operateur: The operateur of this SuiviProdEtapeUt.
        :type operateur: str
        """

        self._operateur = operateur

    @property
    def date_debut(self) -> str:
        """Gets the date_debut of this SuiviProdEtapeUt.


        :return: The date_debut of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._date_debut

    @date_debut.setter
    def date_debut(self, date_debut: str):
        """Sets the date_debut of this SuiviProdEtapeUt.


        :param date_debut: The date_debut of this SuiviProdEtapeUt.
        :type date_debut: str
        """

        self._date_debut = date_debut

    @property
    def date_fin(self) -> str:
        """Gets the date_fin of this SuiviProdEtapeUt.


        :return: The date_fin of this SuiviProdEtapeUt.
        :rtype: str
        """
        return self._date_fin

    @date_fin.setter
    def date_fin(self, date_fin: str):
        """Sets the date_fin of this SuiviProdEtapeUt.


        :param date_fin: The date_fin of this SuiviProdEtapeUt.
        :type date_fin: str
        """

        self._date_fin = date_fin

    @property
    def statut_etape_cl(self) -> int:
        """Gets the statut_etape_cl of this SuiviProdEtapeUt.


        :return: The statut_etape_cl of this SuiviProdEtapeUt.
        :rtype: int
        """
        return self._statut_etape_cl

    @statut_etape_cl.setter
    def statut_etape_cl(self, statut_etape_cl: int):
        """Sets the statut_etape_cl of this SuiviProdEtapeUt.


        :param statut_etape_cl: The statut_etape_cl of this SuiviProdEtapeUt.
        :type statut_etape_cl: int
        """

        self._statut_etape_cl = statut_etape_cl
