# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuiviProdCode(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, id_liste_code: int=None, nom: str=None, desc_en: str=None, desc_fr: str=None):  # noqa: E501
        """SuiviProdCode - a model defined in Swagger

        :param id: The id of this SuiviProdCode.  # noqa: E501
        :type id: int
        :param id_liste_code: The id_liste_code of this SuiviProdCode.  # noqa: E501
        :type id_liste_code: int
        :param nom: The nom of this SuiviProdCode.  # noqa: E501
        :type nom: str
        :param desc_en: The desc_en of this SuiviProdCode.  # noqa: E501
        :type desc_en: str
        :param desc_fr: The desc_fr of this SuiviProdCode.  # noqa: E501
        :type desc_fr: str
        """
        self.swagger_types = {
            'id': int,
            'id_liste_code': int,
            'nom': str,
            'desc_en': str,
            'desc_fr': str
        }

        self.attribute_map = {
            'id': 'id',
            'id_liste_code': 'id_liste_code',
            'nom': 'nom',
            'desc_en': 'desc_en',
            'desc_fr': 'desc_fr'
        }
        self._id = id
        self._id_liste_code = id_liste_code
        self._nom = nom
        self._desc_en = desc_en
        self._desc_fr = desc_fr

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdCode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prod-code of this SuiviProdCode.  # noqa: E501
        :rtype: SuiviProdCode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SuiviProdCode.


        :return: The id of this SuiviProdCode.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SuiviProdCode.


        :param id: The id of this SuiviProdCode.
        :type id: int
        """

        self._id = id

    @property
    def id_liste_code(self) -> int:
        """Gets the id_liste_code of this SuiviProdCode.


        :return: The id_liste_code of this SuiviProdCode.
        :rtype: int
        """
        return self._id_liste_code

    @id_liste_code.setter
    def id_liste_code(self, id_liste_code: int):
        """Sets the id_liste_code of this SuiviProdCode.


        :param id_liste_code: The id_liste_code of this SuiviProdCode.
        :type id_liste_code: int
        """

        self._id_liste_code = id_liste_code

    @property
    def nom(self) -> str:
        """Gets the nom of this SuiviProdCode.


        :return: The nom of this SuiviProdCode.
        :rtype: str
        """
        return self._nom

    @nom.setter
    def nom(self, nom: str):
        """Sets the nom of this SuiviProdCode.


        :param nom: The nom of this SuiviProdCode.
        :type nom: str
        """

        self._nom = nom

    @property
    def desc_en(self) -> str:
        """Gets the desc_en of this SuiviProdCode.


        :return: The desc_en of this SuiviProdCode.
        :rtype: str
        """
        return self._desc_en

    @desc_en.setter
    def desc_en(self, desc_en: str):
        """Sets the desc_en of this SuiviProdCode.


        :param desc_en: The desc_en of this SuiviProdCode.
        :type desc_en: str
        """

        self._desc_en = desc_en

    @property
    def desc_fr(self) -> str:
        """Gets the desc_fr of this SuiviProdCode.


        :return: The desc_fr of this SuiviProdCode.
        :rtype: str
        """
        return self._desc_fr

    @desc_fr.setter
    def desc_fr(self, desc_fr: str):
        """Sets the desc_fr of this SuiviProdCode.


        :param desc_fr: The desc_fr of this SuiviProdCode.
        :type desc_fr: str
        """

        self._desc_fr = desc_fr
