# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuiviProdUniteTravail2NoRel(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, etampe: str=None, dt_c: str=None, dt_m: str=None, id_ut: str=None, id_lot: str=None, date_prevue_fin: str=None, date_debut: str=None, date_fin: str=None, where_clause: str=None, geom: str=None):  # noqa: E501
        """SuiviProdUniteTravail2NoRel - a model defined in Swagger

        :param etampe: The etampe of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type etampe: str
        :param dt_c: The dt_c of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type dt_c: str
        :param dt_m: The dt_m of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type dt_m: str
        :param id_ut: The id_ut of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type id_ut: str
        :param id_lot: The id_lot of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type id_lot: str
        :param date_prevue_fin: The date_prevue_fin of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type date_prevue_fin: str
        :param date_debut: The date_debut of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type date_debut: str
        :param date_fin: The date_fin of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type date_fin: str
        :param where_clause: The where_clause of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type where_clause: str
        :param geom: The geom of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :type geom: str
        """
        self.swagger_types = {
            'etampe': str,
            'dt_c': str,
            'dt_m': str,
            'id_ut': str,
            'id_lot': str,
            'date_prevue_fin': str,
            'date_debut': str,
            'date_fin': str,
            'where_clause': str,
            'geom': str
        }

        self.attribute_map = {
            'etampe': 'etampe',
            'dt_c': 'dt_c',
            'dt_m': 'dt_m',
            'id_ut': 'id_ut',
            'id_lot': 'id_lot',
            'date_prevue_fin': 'date_prevue_fin',
            'date_debut': 'date_debut',
            'date_fin': 'date_fin',
            'where_clause': 'where_clause',
            'geom': 'geom'
        }
        self._etampe = etampe
        self._dt_c = dt_c
        self._dt_m = dt_m
        self._id_ut = id_ut
        self._id_lot = id_lot
        self._date_prevue_fin = date_prevue_fin
        self._date_debut = date_debut
        self._date_fin = date_fin
        self._where_clause = where_clause
        self._geom = geom

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdUniteTravail2NoRel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prod-unite_travail_2-no_rel of this SuiviProdUniteTravail2NoRel.  # noqa: E501
        :rtype: SuiviProdUniteTravail2NoRel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def etampe(self) -> str:
        """Gets the etampe of this SuiviProdUniteTravail2NoRel.


        :return: The etampe of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._etampe

    @etampe.setter
    def etampe(self, etampe: str):
        """Sets the etampe of this SuiviProdUniteTravail2NoRel.


        :param etampe: The etampe of this SuiviProdUniteTravail2NoRel.
        :type etampe: str
        """

        self._etampe = etampe

    @property
    def dt_c(self) -> str:
        """Gets the dt_c of this SuiviProdUniteTravail2NoRel.


        :return: The dt_c of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._dt_c

    @dt_c.setter
    def dt_c(self, dt_c: str):
        """Sets the dt_c of this SuiviProdUniteTravail2NoRel.


        :param dt_c: The dt_c of this SuiviProdUniteTravail2NoRel.
        :type dt_c: str
        """

        self._dt_c = dt_c

    @property
    def dt_m(self) -> str:
        """Gets the dt_m of this SuiviProdUniteTravail2NoRel.


        :return: The dt_m of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._dt_m

    @dt_m.setter
    def dt_m(self, dt_m: str):
        """Sets the dt_m of this SuiviProdUniteTravail2NoRel.


        :param dt_m: The dt_m of this SuiviProdUniteTravail2NoRel.
        :type dt_m: str
        """

        self._dt_m = dt_m

    @property
    def id_ut(self) -> str:
        """Gets the id_ut of this SuiviProdUniteTravail2NoRel.


        :return: The id_ut of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._id_ut

    @id_ut.setter
    def id_ut(self, id_ut: str):
        """Sets the id_ut of this SuiviProdUniteTravail2NoRel.


        :param id_ut: The id_ut of this SuiviProdUniteTravail2NoRel.
        :type id_ut: str
        """

        self._id_ut = id_ut

    @property
    def id_lot(self) -> str:
        """Gets the id_lot of this SuiviProdUniteTravail2NoRel.


        :return: The id_lot of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._id_lot

    @id_lot.setter
    def id_lot(self, id_lot: str):
        """Sets the id_lot of this SuiviProdUniteTravail2NoRel.


        :param id_lot: The id_lot of this SuiviProdUniteTravail2NoRel.
        :type id_lot: str
        """

        self._id_lot = id_lot

    @property
    def date_prevue_fin(self) -> str:
        """Gets the date_prevue_fin of this SuiviProdUniteTravail2NoRel.


        :return: The date_prevue_fin of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._date_prevue_fin

    @date_prevue_fin.setter
    def date_prevue_fin(self, date_prevue_fin: str):
        """Sets the date_prevue_fin of this SuiviProdUniteTravail2NoRel.


        :param date_prevue_fin: The date_prevue_fin of this SuiviProdUniteTravail2NoRel.
        :type date_prevue_fin: str
        """

        self._date_prevue_fin = date_prevue_fin

    @property
    def date_debut(self) -> str:
        """Gets the date_debut of this SuiviProdUniteTravail2NoRel.


        :return: The date_debut of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._date_debut

    @date_debut.setter
    def date_debut(self, date_debut: str):
        """Sets the date_debut of this SuiviProdUniteTravail2NoRel.


        :param date_debut: The date_debut of this SuiviProdUniteTravail2NoRel.
        :type date_debut: str
        """

        self._date_debut = date_debut

    @property
    def date_fin(self) -> str:
        """Gets the date_fin of this SuiviProdUniteTravail2NoRel.


        :return: The date_fin of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._date_fin

    @date_fin.setter
    def date_fin(self, date_fin: str):
        """Sets the date_fin of this SuiviProdUniteTravail2NoRel.


        :param date_fin: The date_fin of this SuiviProdUniteTravail2NoRel.
        :type date_fin: str
        """

        self._date_fin = date_fin

    @property
    def where_clause(self) -> str:
        """Gets the where_clause of this SuiviProdUniteTravail2NoRel.


        :return: The where_clause of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._where_clause

    @where_clause.setter
    def where_clause(self, where_clause: str):
        """Sets the where_clause of this SuiviProdUniteTravail2NoRel.


        :param where_clause: The where_clause of this SuiviProdUniteTravail2NoRel.
        :type where_clause: str
        """

        self._where_clause = where_clause

    @property
    def geom(self) -> str:
        """Gets the geom of this SuiviProdUniteTravail2NoRel.


        :return: The geom of this SuiviProdUniteTravail2NoRel.
        :rtype: str
        """
        return self._geom

    @geom.setter
    def geom(self, geom: str):
        """Sets the geom of this SuiviProdUniteTravail2NoRel.


        :param geom: The geom of this SuiviProdUniteTravail2NoRel.
        :type geom: str
        """

        self._geom = geom
