# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suivi_prod_executant import SuiviProdExecutant  # noqa: F401,E501
from swagger_server.models.suivi_prod_featuretype import SuiviProdFeaturetype  # noqa: F401,E501
from swagger_server.models.suivi_prod_unite_travail2_full_rel import SuiviProdUniteTravail2FullRel  # noqa: F401,E501
from swagger_server import util


class SuiviProdlotfullRelRelation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, executant: SuiviProdExecutant=None, unite_travail_2: List[SuiviProdUniteTravail2FullRel]=None, feature_type: List[SuiviProdFeaturetype]=None):  # noqa: E501
        """SuiviProdlotfullRelRelation - a model defined in Swagger

        :param executant: The executant of this SuiviProdlotfullRelRelation.  # noqa: E501
        :type executant: SuiviProdExecutant
        :param unite_travail_2: The unite_travail_2 of this SuiviProdlotfullRelRelation.  # noqa: E501
        :type unite_travail_2: List[SuiviProdUniteTravail2FullRel]
        :param feature_type: The feature_type of this SuiviProdlotfullRelRelation.  # noqa: E501
        :type feature_type: List[SuiviProdFeaturetype]
        """
        self.swagger_types = {
            'executant': SuiviProdExecutant,
            'unite_travail_2': List[SuiviProdUniteTravail2FullRel],
            'feature_type': List[SuiviProdFeaturetype]
        }

        self.attribute_map = {
            'executant': 'executant',
            'unite_travail_2': 'unite_travail_2',
            'feature_type': 'feature_type'
        }
        self._executant = executant
        self._unite_travail_2 = unite_travail_2
        self._feature_type = feature_type

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProdlotfullRelRelation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_prodlotfull_rel_relation of this SuiviProdlotfullRelRelation.  # noqa: E501
        :rtype: SuiviProdlotfullRelRelation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def executant(self) -> SuiviProdExecutant:
        """Gets the executant of this SuiviProdlotfullRelRelation.


        :return: The executant of this SuiviProdlotfullRelRelation.
        :rtype: SuiviProdExecutant
        """
        return self._executant

    @executant.setter
    def executant(self, executant: SuiviProdExecutant):
        """Sets the executant of this SuiviProdlotfullRelRelation.


        :param executant: The executant of this SuiviProdlotfullRelRelation.
        :type executant: SuiviProdExecutant
        """

        self._executant = executant

    @property
    def unite_travail_2(self) -> List[SuiviProdUniteTravail2FullRel]:
        """Gets the unite_travail_2 of this SuiviProdlotfullRelRelation.


        :return: The unite_travail_2 of this SuiviProdlotfullRelRelation.
        :rtype: List[SuiviProdUniteTravail2FullRel]
        """
        return self._unite_travail_2

    @unite_travail_2.setter
    def unite_travail_2(self, unite_travail_2: List[SuiviProdUniteTravail2FullRel]):
        """Sets the unite_travail_2 of this SuiviProdlotfullRelRelation.


        :param unite_travail_2: The unite_travail_2 of this SuiviProdlotfullRelRelation.
        :type unite_travail_2: List[SuiviProdUniteTravail2FullRel]
        """

        self._unite_travail_2 = unite_travail_2

    @property
    def feature_type(self) -> List[SuiviProdFeaturetype]:
        """Gets the feature_type of this SuiviProdlotfullRelRelation.


        :return: The feature_type of this SuiviProdlotfullRelRelation.
        :rtype: List[SuiviProdFeaturetype]
        """
        return self._feature_type

    @feature_type.setter
    def feature_type(self, feature_type: List[SuiviProdFeaturetype]):
        """Sets the feature_type of this SuiviProdlotfullRelRelation.


        :param feature_type: The feature_type of this SuiviProdlotfullRelRelation.
        :type feature_type: List[SuiviProdFeaturetype]
        """

        self._feature_type = feature_type
