# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SuivProdRequeteSql(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sql: str=None):  # noqa: E501
        """SuivProdRequeteSql - a model defined in Swagger

        :param sql: The sql of this SuivProdRequeteSql.  # noqa: E501
        :type sql: str
        """
        self.swagger_types = {
            'sql': str
        }

        self.attribute_map = {
            'sql': 'sql'
        }
        self._sql = sql

    @classmethod
    def from_dict(cls, dikt) -> 'SuivProdRequeteSql':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suiv_prod-requete_sql of this SuivProdRequeteSql.  # noqa: E501
        :rtype: SuivProdRequeteSql
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sql(self) -> str:
        """Gets the sql of this SuivProdRequeteSql.


        :return: The sql of this SuivProdRequeteSql.
        :rtype: str
        """
        return self._sql

    @sql.setter
    def sql(self, sql: str):
        """Sets the sql of this SuivProdRequeteSql.


        :param sql: The sql of this SuivProdRequeteSql.
        :type sql: str
        """

        self._sql = sql
