# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.suivi_prod_etape_ut import SuiviProdEtapeUt  # noqa: F401,E501
from swagger_server.models.suivi_prod_sous_unite_travail_full_rel import SuiviProdSousUniteTravailFullRel  # noqa: F401,E501
from swagger_server import util


class SuiviProduniteTravail2fullRelRelation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, etape_ut: List[SuiviProdEtapeUt]=None, sous_unite_travail: List[SuiviProdSousUniteTravailFullRel]=None):  # noqa: E501
        """SuiviProduniteTravail2fullRelRelation - a model defined in Swagger

        :param etape_ut: The etape_ut of this SuiviProduniteTravail2fullRelRelation.  # noqa: E501
        :type etape_ut: List[SuiviProdEtapeUt]
        :param sous_unite_travail: The sous_unite_travail of this SuiviProduniteTravail2fullRelRelation.  # noqa: E501
        :type sous_unite_travail: List[SuiviProdSousUniteTravailFullRel]
        """
        self.swagger_types = {
            'etape_ut': List[SuiviProdEtapeUt],
            'sous_unite_travail': List[SuiviProdSousUniteTravailFullRel]
        }

        self.attribute_map = {
            'etape_ut': 'etape_ut',
            'sous_unite_travail': 'sous_unite_travail'
        }
        self._etape_ut = etape_ut
        self._sous_unite_travail = sous_unite_travail

    @classmethod
    def from_dict(cls, dikt) -> 'SuiviProduniteTravail2fullRelRelation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The suivi_produnite_travail_2full_rel_relation of this SuiviProduniteTravail2fullRelRelation.  # noqa: E501
        :rtype: SuiviProduniteTravail2fullRelRelation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def etape_ut(self) -> List[SuiviProdEtapeUt]:
        """Gets the etape_ut of this SuiviProduniteTravail2fullRelRelation.


        :return: The etape_ut of this SuiviProduniteTravail2fullRelRelation.
        :rtype: List[SuiviProdEtapeUt]
        """
        return self._etape_ut

    @etape_ut.setter
    def etape_ut(self, etape_ut: List[SuiviProdEtapeUt]):
        """Sets the etape_ut of this SuiviProduniteTravail2fullRelRelation.


        :param etape_ut: The etape_ut of this SuiviProduniteTravail2fullRelRelation.
        :type etape_ut: List[SuiviProdEtapeUt]
        """

        self._etape_ut = etape_ut

    @property
    def sous_unite_travail(self) -> List[SuiviProdSousUniteTravailFullRel]:
        """Gets the sous_unite_travail of this SuiviProduniteTravail2fullRelRelation.


        :return: The sous_unite_travail of this SuiviProduniteTravail2fullRelRelation.
        :rtype: List[SuiviProdSousUniteTravailFullRel]
        """
        return self._sous_unite_travail

    @sous_unite_travail.setter
    def sous_unite_travail(self, sous_unite_travail: List[SuiviProdSousUniteTravailFullRel]):
        """Sets the sous_unite_travail of this SuiviProduniteTravail2fullRelRelation.


        :param sous_unite_travail: The sous_unite_travail of this SuiviProduniteTravail2fullRelRelation.
        :type sous_unite_travail: List[SuiviProdSousUniteTravailFullRel]
        """

        self._sous_unite_travail = sous_unite_travail
