# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SystemeEnvsInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, env: str=None, url: str=None):  # noqa: E501
        """SystemeEnvsInner - a model defined in Swagger

        :param env: The env of this SystemeEnvsInner.  # noqa: E501
        :type env: str
        :param url: The url of this SystemeEnvsInner.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'env': str,
            'url': str
        }

        self.attribute_map = {
            'env': 'env',
            'url': 'url'
        }
        self._env = env
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'SystemeEnvsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The systeme_envs_inner of this SystemeEnvsInner.  # noqa: E501
        :rtype: SystemeEnvsInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def env(self) -> str:
        """Gets the env of this SystemeEnvsInner.


        :return: The env of this SystemeEnvsInner.
        :rtype: str
        """
        return self._env

    @env.setter
    def env(self, env: str):
        """Sets the env of this SystemeEnvsInner.


        :param env: The env of this SystemeEnvsInner.
        :type env: str
        """

        self._env = env

    @property
    def url(self) -> str:
        """Gets the url of this SystemeEnvsInner.


        :return: The url of this SystemeEnvsInner.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this SystemeEnvsInner.


        :param url: The url of this SystemeEnvsInner.
        :type url: str
        """

        self._url = url
