# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.systeme_liste_contenants_fichiers_list_file import SystemeListeContenantsFichiersListFile  # noqa: F401,E501
from swagger_server.models.systeme_liste_contenants_fichiers_list_folder import SystemeListeContenantsFichiersListFolder  # noqa: F401,E501
from swagger_server import util


class SystemeListeContenantsFichiers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, list_file: List[SystemeListeContenantsFichiersListFile]=None, list_folder: List[SystemeListeContenantsFichiersListFolder]=None):  # noqa: E501
        """SystemeListeContenantsFichiers - a model defined in Swagger

        :param list_file: The list_file of this SystemeListeContenantsFichiers.  # noqa: E501
        :type list_file: List[SystemeListeContenantsFichiersListFile]
        :param list_folder: The list_folder of this SystemeListeContenantsFichiers.  # noqa: E501
        :type list_folder: List[SystemeListeContenantsFichiersListFolder]
        """
        self.swagger_types = {
            'list_file': List[SystemeListeContenantsFichiersListFile],
            'list_folder': List[SystemeListeContenantsFichiersListFolder]
        }

        self.attribute_map = {
            'list_file': 'list_file',
            'list_folder': 'list_folder'
        }
        self._list_file = list_file
        self._list_folder = list_folder

    @classmethod
    def from_dict(cls, dikt) -> 'SystemeListeContenantsFichiers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The systeme_liste_contenants_fichiers of this SystemeListeContenantsFichiers.  # noqa: E501
        :rtype: SystemeListeContenantsFichiers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_file(self) -> List[SystemeListeContenantsFichiersListFile]:
        """Gets the list_file of this SystemeListeContenantsFichiers.


        :return: The list_file of this SystemeListeContenantsFichiers.
        :rtype: List[SystemeListeContenantsFichiersListFile]
        """
        return self._list_file

    @list_file.setter
    def list_file(self, list_file: List[SystemeListeContenantsFichiersListFile]):
        """Sets the list_file of this SystemeListeContenantsFichiers.


        :param list_file: The list_file of this SystemeListeContenantsFichiers.
        :type list_file: List[SystemeListeContenantsFichiersListFile]
        """

        self._list_file = list_file

    @property
    def list_folder(self) -> List[SystemeListeContenantsFichiersListFolder]:
        """Gets the list_folder of this SystemeListeContenantsFichiers.


        :return: The list_folder of this SystemeListeContenantsFichiers.
        :rtype: List[SystemeListeContenantsFichiersListFolder]
        """
        return self._list_folder

    @list_folder.setter
    def list_folder(self, list_folder: List[SystemeListeContenantsFichiersListFolder]):
        """Sets the list_folder of this SystemeListeContenantsFichiers.


        :param list_folder: The list_folder of this SystemeListeContenantsFichiers.
        :type list_folder: List[SystemeListeContenantsFichiersListFolder]
        """

        self._list_folder = list_folder
