# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SystemeListeContenantsFichiersListFolder(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, last_modified: str=None):  # noqa: E501
        """SystemeListeContenantsFichiersListFolder - a model defined in Swagger

        :param name: The name of this SystemeListeContenantsFichiersListFolder.  # noqa: E501
        :type name: str
        :param last_modified: The last_modified of this SystemeListeContenantsFichiersListFolder.  # noqa: E501
        :type last_modified: str
        """
        self.swagger_types = {
            'name': str,
            'last_modified': str
        }

        self.attribute_map = {
            'name': 'name',
            'last_modified': 'last_modified'
        }
        self._name = name
        self._last_modified = last_modified

    @classmethod
    def from_dict(cls, dikt) -> 'SystemeListeContenantsFichiersListFolder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The systeme_liste_contenants_fichiers_list_folder of this SystemeListeContenantsFichiersListFolder.  # noqa: E501
        :rtype: SystemeListeContenantsFichiersListFolder
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this SystemeListeContenantsFichiersListFolder.


        :return: The name of this SystemeListeContenantsFichiersListFolder.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SystemeListeContenantsFichiersListFolder.


        :param name: The name of this SystemeListeContenantsFichiersListFolder.
        :type name: str
        """

        self._name = name

    @property
    def last_modified(self) -> str:
        """Gets the last_modified of this SystemeListeContenantsFichiersListFolder.


        :return: The last_modified of this SystemeListeContenantsFichiersListFolder.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: str):
        """Sets the last_modified of this SystemeListeContenantsFichiersListFolder.


        :param last_modified: The last_modified of this SystemeListeContenantsFichiersListFolder.
        :type last_modified: str
        """

        self._last_modified = last_modified
