# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SystemeRessRequete(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, fichiers: List[str]=None, chemin_recherche: List[str]=None):  # noqa: E501
        """SystemeRessRequete - a model defined in Swagger

        :param fichiers: The fichiers of this SystemeRessRequete.  # noqa: E501
        :type fichiers: List[str]
        :param chemin_recherche: The chemin_recherche of this SystemeRessRequete.  # noqa: E501
        :type chemin_recherche: List[str]
        """
        self.swagger_types = {
            'fichiers': List[str],
            'chemin_recherche': List[str]
        }

        self.attribute_map = {
            'fichiers': 'fichiers',
            'chemin_recherche': 'chemin_recherche'
        }
        self._fichiers = fichiers
        self._chemin_recherche = chemin_recherche

    @classmethod
    def from_dict(cls, dikt) -> 'SystemeRessRequete':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The systeme_ress_requete of this SystemeRessRequete.  # noqa: E501
        :rtype: SystemeRessRequete
        """
        return util.deserialize_model(dikt, cls)

    @property
    def fichiers(self) -> List[str]:
        """Gets the fichiers of this SystemeRessRequete.


        :return: The fichiers of this SystemeRessRequete.
        :rtype: List[str]
        """
        return self._fichiers

    @fichiers.setter
    def fichiers(self, fichiers: List[str]):
        """Sets the fichiers of this SystemeRessRequete.


        :param fichiers: The fichiers of this SystemeRessRequete.
        :type fichiers: List[str]
        """

        self._fichiers = fichiers

    @property
    def chemin_recherche(self) -> List[str]:
        """Gets the chemin_recherche of this SystemeRessRequete.


        :return: The chemin_recherche of this SystemeRessRequete.
        :rtype: List[str]
        """
        return self._chemin_recherche

    @chemin_recherche.setter
    def chemin_recherche(self, chemin_recherche: List[str]):
        """Sets the chemin_recherche of this SystemeRessRequete.


        :param chemin_recherche: The chemin_recherche of this SystemeRessRequete.
        :type chemin_recherche: List[str]
        """

        self._chemin_recherche = chemin_recherche
