# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SystemeListeContenantsFichiersListFile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, size: int=None, last_modified: str=None):  # noqa: E501
        """SystemeListeContenantsFichiersListFile - a model defined in Swagger

        :param name: The name of this SystemeListeContenantsFichiersListFile.  # noqa: E501
        :type name: str
        :param size: The size of this SystemeListeContenantsFichiersListFile.  # noqa: E501
        :type size: int
        :param last_modified: The last_modified of this SystemeListeContenantsFichiersListFile.  # noqa: E501
        :type last_modified: str
        """
        self.swagger_types = {
            'name': str,
            'size': int,
            'last_modified': str
        }

        self.attribute_map = {
            'name': 'name',
            'size': 'size',
            'last_modified': 'last_modified'
        }
        self._name = name
        self._size = size
        self._last_modified = last_modified

    @classmethod
    def from_dict(cls, dikt) -> 'SystemeListeContenantsFichiersListFile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The systeme_liste_contenants_fichiers_list_file of this SystemeListeContenantsFichiersListFile.  # noqa: E501
        :rtype: SystemeListeContenantsFichiersListFile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this SystemeListeContenantsFichiersListFile.


        :return: The name of this SystemeListeContenantsFichiersListFile.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SystemeListeContenantsFichiersListFile.


        :param name: The name of this SystemeListeContenantsFichiersListFile.
        :type name: str
        """

        self._name = name

    @property
    def size(self) -> int:
        """Gets the size of this SystemeListeContenantsFichiersListFile.


        :return: The size of this SystemeListeContenantsFichiersListFile.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this SystemeListeContenantsFichiersListFile.


        :param size: The size of this SystemeListeContenantsFichiersListFile.
        :type size: int
        """

        self._size = size

    @property
    def last_modified(self) -> str:
        """Gets the last_modified of this SystemeListeContenantsFichiersListFile.


        :return: The last_modified of this SystemeListeContenantsFichiersListFile.
        :rtype: str
        """
        return self._last_modified

    @last_modified.setter
    def last_modified(self, last_modified: str):
        """Sets the last_modified of this SystemeListeContenantsFichiersListFile.


        :param last_modified: The last_modified of this SystemeListeContenantsFichiersListFile.
        :type last_modified: str
        """

        self._last_modified = last_modified
